### ISSUE TITLE
Getting /random from theanarchistlibrary.org

### ISSUE THREAD

**Issue by melmothx** [spencerthayer/AnonBoard#1]
Honestly doesn't look like a good idea, not so much for wasting others' resources, but because you're relying on an external service which may or may be not up, and that server itself doesn't look like a good source of entropy anyway. Just don't do that.

**Comment by spencerthayer** [comment]
> relying on an external service which may or may be not up

Yup. I've already experienced the service slowing down the generation of the SMP list. I'm working on just a random string maker for the SMP. It'll be faster too.

**Comment by spencerthayer** [comment]
The random string strong pass Codebook is integrated into the site.
