### ISSUE TITLE
Support for databases?

### ISSUE THREAD

**Issue by montyanderson** [spencerthayer/AnonBoard#2]
Why is it purely flat-file? It doesn't scale well at all.

**Comment by spencerthayer** [comment]
It's flat-file because it'll run on most hardware with minimal configuration. But yes, it does not scale. I'm building into an ability to switch a DB. But that'll be later down the road.

**Comment by spencerthayer** [comment]
This is now in the Project Milestones and will likely happen in version 1.5.
https://github.com/spencerthayer/AnonBoard/milestone/2
